### ISSUE TITLE
Strange issue in WAMP

### ISSUE THREAD

**Issue by kishu27** [peej/tonic#101]
Any file change through a windows editor on the example hello script generates weird errors.  

I tried analyzing the $uri array in line 173 of Application.php, it has an extra element : empty string right there at line 173 in Application.php

Error Log:

> Warning: array_combine() [function.array-combine]: Both parameters should have an equal number of elements in C:\wamp\www\peej-tonic-96f6b39\src\Tonic\Application.php on line 173
> 
> Warning: array_shift() expects parameter 1 to be array, boolean given in C:\wamp\www\peej-tonic-96f6b39\src\Tonic\Application.php on line 175
> 
> Catchable fatal error: Argument 3 passed to Tonic\Resource::__construct() must be an array, boolean given, called in C:\wamp\www\peej-tonic-96f6b39\src\Tonic\Application.php on line 186 and defined in C:\wamp\www\peej-tonic-96f6b39\src\Tonic\Resource.php on line 14

In my best guess this is a CRLF character problem. As soon as the new line is changed to CRLF, this starts happening.  The exact steps to reproduce: 
1. Run PHP on WAMP (Windows 7 64 bit Home Edition, PHP 5.3 in WAMP)
2. Run the Tyrell Application in the example setup provided in downloads
3. Change anything in the Hello example (just any file change and save)
4. Access the /hello URL on GET and notice the error

The error is not reproduced when same file is ran on a *nix setup.

**Comment by RentecVik** [comment]
Working on a legacy system and encountered this problem. The simplest solution has been to ensure the code editor enforces Unix style line endings, thus avoiding the breakage.
